minimum_pre_commit_version: 4.0.0
default_language_version:
    python: python3.10

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies: ["packaging>=21.0", "pytest>=7.0.0", "typer>=0.15.3"]
        #exclude: '^tests/'
        args: [--disallow-untyped-defs]
        # `--follow-imports=silent` stop complaints about problems within followed imports

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: check-added-large-files
      - id: debug-statements
      - id: check-ast

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      # Run the linter and make fixes, then the formatter
      # replaces flake8, Black, isort, pydocstyle, pyupgrade, etc.
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
