[project]
name = "netvelocimeter"
version = "0.1.0"
description = "A library for measuring network performance metrics"
authors = [
    {name = "Dale Phurrough", email = "dale@hidale.com"},
]
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "packaging>=21.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: System :: Networking",
    "Topic :: System :: Monitoring",
]

[project.urls]
"Homepage" = "https://github.com/diablodale/netvelocimeter"
"Bug Tracker" = "https://github.com/diablodale/netvelocimeter/issues"

[project.optional-dependencies]
dev-requirements = {file = "dev-requirements.txt"}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["netvelocimeter"]
